# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
   def setupUi(self, Dialog):
      Dialog.setObjectName("Give-a-Little")
      Dialog.resize(1124, 845)
      Dialog.setAutoFillBackground(False)
      self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
      self.horizontalLayoutWidget.setGeometry(QtCore.QRect(730, 0, 391, 51))
      self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
      self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
      self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
      self.horizontalLayout.setSpacing(20)
      self.horizontalLayout.setObjectName("horizontalLayout")
      self.btnLogin = QtWidgets.QPushButton(self.horizontalLayoutWidget)
      self.btnLogin.setObjectName("btnLogin")
      self.horizontalLayout.addWidget(self.btnLogin)
      self.btnLogin.clicked.connect(btnLogin_clicked)
      self.btnRegister = QtWidgets.QPushButton(self.horizontalLayoutWidget)
      self.btnRegister.setObjectName("btnRegister")
      self.horizontalLayout.addWidget(self.btnRegister)
      self.btnRegister.clicked.connect(btnRegister_clicked)

      self.retranslateUi(Dialog)
      QtCore.QMetaObject.connectSlotsByName(Dialog)

   def retranslateUi(self, Dialog):
      _translate = QtCore.QCoreApplication.translate
      Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
      self.btnLogin.setText(_translate("Dialog", "Login"))
      self.btnRegister.setText(_translate("Dialog", "Register"))

def btnLogin_clicked():
   print ("Button login clicked")

def btnRegister_clicked():
   print ("Button register clicked")