# CircleCI configuration file

version: 2.1
orbs: 
  codecov: codecov/codecov@3.2.3
jobs:
  run-and-test:
    docker:
      - image: cimg/python:3.9.6
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    dependencies:
      pre:
        - sudo apt-get install apt -y
        - sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y
        - sudo apt-get update -y; true
        - sudo apt-get install -y qt54webkit libwebkit-dev libgstreamer0.10-dev
        - echo "/opt/qt54/bin/qt54-env.sh" >> ~/.circlerc
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install coverage
      - run: 
          name: Run tests
          command: |
            coverage run -m unittest discover
            coverage report
      - codecov/upload
        

workflows:
  version: 2.1
  tests-coverage:
    jobs:
      - run-and-test