# CircleCI configuration file

version: 2.1
orbs: 
  codecov: codecov/codecov@3.2.3
jobs:
  run-and-test:
    docker:
      - image: cimg/python:3.9.6
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install coverage
      - run: 
          name: Run tests
          command: |
            coverage run -m unittest discover
            coverage report
      - codecov/upload

workflows:
  version: 2.1
  tests-coverage:
    jobs:
      - run-and-test